### ISSUE TITLE
[FEATURE] Allow more functions in services to be overridden

### ISSUE THREAD

**Issue by roberlander2** [rokwire/app-flutter-plugin#1]
**Is your feature request related to a problem? Please describe.**
Some functions and getters in services cannot be overridden using the current version of the plugin.

**Describe the solution you'd like**
Make certain getters and functions able to be overridden to improve ease of implementation.

**Describe alternatives you've considered**
The implementing project could just reimplement these functions that cannot be overridden, but the reimplementation would only introduce minor differences from the plugin's implementation.

**Additional context**

**Comment by mihail-varbanov** [comment]
Hi @roberlander2. Everything looks pretty good in the [issues/ID-1](https://github.com/rokwire/app-flutter-plugin/tree/issues/ID-1) branch so far. I appreciate the way you have taken: to create an issue and do the work in a standalone branch for this issue. I just wanted to give you a hint that if you add "#1" in your commit texts GIT will associate this commit to the referred issue number and you will see it listed in the issue's history. You could take a look at any of the [illinois-app](https://github.com/rokwire/illinois-app) repo issues to see this feature in action.

**Comment by roberlander2** [comment]
Hi @mihail-varbanov, I want to ask about the notification strings used by `notification_service.dart`.

Does the prefix need to match the application ID of a client implementing the plugin?

For example, if a client with app ID `new_app` implements the plugin, would `static const String notifyLoginSucceeded    = "edu.illinois.rokwire.auth2.login.succeeded";` need to be overridden to be `"new_app.auth2.login.succeeded"`?

If the prefixes of these strings do not need to match the app ID, can we remove the prefixes to make this clearer?

Please let me know your opinion on this. Thanks!

**Comment by mihail-varbanov** [comment]
Hi @roberlander2,

The notification names can take arbitrary values. The only requirement is they to be unique so that to avoid conflicts when two independant services that do not know each other use the same notification name.

For example, consider the case if Styles and Config services use  `content.changed` as notification name when they get updated. A listener for Config updates would get notified when Styles service gets changed, that is not good.

Please consider another case - a Flutter application includes a number of different plugins, each of which uses notification service to fire some events. In order to avoid a conflict between different packages it is good to include the package name/identifier inside the notification name. That's why the notification names in the plugin always start with `edu.illinois.rokwire`, then we have a service identifier (e.g. `config`, `inbox`, etc.), and only then the name of the actual event.

In OSF Oncall Connect app it is fine to listen for any plugin events, e.g. `edu.illinois.rokwire.config.changed`. In your app side, if you need to define your own notification I would recommend to use the same model, e.g. `com.rokmetro.osf.oncall.connect.config.something_happen` if you override Rokwire's Config service and need to fire some different config name, or `com.rokmetro.osf.oncall.connect.health.illnesses.changed` that your Health service currently fires.

Once again, this is not some strong requirement, this is just some a naming convention for avoiding conflicts in notification names.

**Comment by roberlander2** [comment]
@mihail-varbanov, thank you for the clarification!

**Comment by roberlander2** [comment]
Thanks @mihail-varbanov, I will keep this in mind for future updates. I created a PR for my changes now that I have gotten my build working. Please let me know if you would rather not merge the "environment" typo fix, this change is not required for my build.
